# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'

target 'GcloudCam' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GcloudCam

  target 'GcloudCam-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNFS', :path => '../node_modules/react-native-fs'

  end

end

# target 'GcloudCam-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for GcloudCam-tvOS

#   target 'GcloudCam-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
